from extensions import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(120), unique = True, nullable = False)
    password = db.Column(db.String(20), nullable = False)
    spotify_access_token = db.Column(db.String(500), nullable = True)
    spotify_refresh_token = db.Column(db.String(500), nullable = True)
    spotify_token_expires_at = db.Column(db.DateTime, nullable = True)


class TransactionAnalysis(db.Model):
    id = db.Column(db.String(32), primary_key=True)
    user_id = db.Column(db.Integer, nullable=True)
    hostname = db.Column(db.String(255), nullable=False, index=True)
    page_url_hash = db.Column(db.String(64), nullable=False, index=True)
    platform_name = db.Column(db.String(120), nullable=True)
    purchase_type = db.Column(db.String(40), nullable=False, default="unknown")
    detected_price = db.Column(db.Float, nullable=True)
    detected_currency = db.Column(db.String(12), nullable=True)
    result_json = db.Column(db.Text, nullable=False)
    citations_json = db.Column(db.Text, nullable=False)
    cache_status = db.Column(db.String(20), nullable=False, default="none")
    created_at = db.Column(db.DateTime, nullable=False)
    expires_at = db.Column(db.DateTime, nullable=True)
    source_check_status = db.Column(db.String(20), nullable=False, default="unavailable")


class SiteReport(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url_hash = db.Column(db.String(64), nullable=False, unique=True, index=True)
    display_url = db.Column(db.String(500), nullable=False)
    hostname = db.Column(db.String(255), nullable=False, index=True)
    page_title = db.Column(db.String(300), nullable=True)
    user_note = db.Column(db.String(500), nullable=True)
    local_signals_json = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, nullable=True)
    status = db.Column(db.String(30), nullable=False, default="pending_review", index=True)
    submission_count = db.Column(db.Integer, nullable=False, default=1)
    first_reported_at = db.Column(db.DateTime, nullable=False)
    last_reported_at = db.Column(db.DateTime, nullable=False)
    reviewed_at = db.Column(db.DateTime, nullable=True)
    reviewed_by_user_id = db.Column(db.Integer, nullable=True)
    reviewer_notes = db.Column(db.String(500), nullable=True)
    ai_recommendation = db.Column(db.String(40), nullable=True)
    ai_confidence = db.Column(db.Integer, nullable=True)
    ai_reason = db.Column(db.String(500), nullable=True)
    ai_category = db.Column(db.String(80), nullable=True)
    ai_checked_at = db.Column(db.DateTime, nullable=True)


class DataPoint(db.Model):
    key = db.Column(db.String(120), primary_key=True)
    label = db.Column(db.String(200), nullable=False)
    figure_low = db.Column(db.Float, nullable=True)
    figure_high = db.Column(db.Float, nullable=True)
    figure_point = db.Column(db.Float, nullable=True)
    unit = db.Column(db.String(40), nullable=True)
    currency = db.Column(db.String(12), nullable=True)
    confidence_score = db.Column(db.Integer, nullable=False, default=0)
    confidence_band = db.Column(db.String(20), nullable=False, default="INSUFFICIENT")
    sources_json = db.Column(db.Text, nullable=False)
    methodology_notes = db.Column(db.Text, nullable=True)
    contradictions = db.Column(db.Text, nullable=True)
    dimension_scores_json = db.Column(db.Text, nullable=False)
    dimension_evidence_json = db.Column(db.Text, nullable=False)
    last_updated = db.Column(db.DateTime, nullable=False)
    display_json = db.Column(db.Text, nullable=False)
